### PR TITLE
Use the before emit hook to check if files exist

### PR DESCRIPTION
**Pull request by sunilbandla**
- Add an option to use this hook.
- When this plugin is used with other loaders such as ts-loader and
vue-loader, this option improves the overall build time. In our case,
the build time reduced by 5-10 seconds.

Tests passed locally.

### CODE REVIEW

**Comment by Urthen** [comment]
Thanks for optimizing!

My only problem with this is you left in the require to `perf_hooks` with no fallback if it doesn't exist. `perf_hooks` was added in 8.5.0 and I'd like to maintain backwards compatibility to at least 6.x for a while still.

If you can either remove that or make it optional, the rest looks good.

**Comment by sunilbandla** [comment]
Thanks, I removed that commit.

**Comment by sunilbandla** [comment]
@Urthen Is this good to merge?

**Comment by sunilbandla** [comment]
Thanks for merging. I will add this option to the readme after testing the next release for a few weeks. 

Also, there's another possible improvement that can be made. Some folders are being read multiple times from the filesystem. It does not have a huge performance impact though. I will submit a PR for that soon.

**Comment by sunilbandla** [comment]
@Urthen Could you please release this change?

**Comment by Urthen** [comment]
Sorry this took so long, fell off my radar over the holidays.

2.2.0 is released.

**Pull request merged**
